**TITLE OF PROJECT:WINEQUALITY PREDICTION USING SUPPORT VECTOR MACHINE**


Objective

OBJECTIVE IS TO FIND THE PREDICTION
THIS SET HAVE 12 VARIABLES:
1 - fixed acidity
2 - volatile acidity
3 - citric acid
4 - residual sugar
5 - chlorides
6 - free sulfur dioxide
7 - total sulfur dioxide
8 - density
9 - pH
10 - sulphates
11 - alcohol
12 - quality


Data Source FROM YUI FOUNDATION GITHUB

Import Library

In [ ]:
import pandas as pd
import numpy as np

Import Data

In [ ]:
df=pd.read_csv('winequalityN.csv')

Describe Data

In [ ]:
df=df.dropna()

In [ ]:
df.head()

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0  white            7.0              0.27         0.36            20.7   
1  white            6.3              0.30         0.34             1.6   
2  white            8.1              0.28         0.40             6.9   
3  white            7.2              0.23         0.32             8.5   
4  white            7.2              0.23         0.32             8.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00   
1      0.049                 14.0                 132.0   0.9940  3.30   
2      0.050                 30.0                  97.0   0.9951  3.26   
3      0.058                 47.0                 186.0   0.9956  3.19   
4      0.058                 47.0                 186.0   0.9956  3.19   

   sulphates  alcohol  quality  
0       0.45      8.8        6  
1       0.49      9.5        6  
2       0.44     10.1        6  
3       0.40      9.9        6  
4       0.40      9.9        6

In [ ]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    6463.000000       6463.000000  6463.000000     6463.000000   
mean        7.217755          0.339589     0.318758        5.443958   
std         1.297913          0.164639     0.145252        4.756852   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.400000          0.230000     0.250000        1.800000   
50%         7.000000          0.290000     0.310000        3.000000   
75%         7.700000          0.400000     0.390000        8.100000   
max        15.900000          1.580000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  6463.000000          6463.000000           6463.000000  6463.000000   
mean      0.056056            30.516865            115.694492     0.994698   
std       0.035076            17.758815             56.526736     0.003001   
min       0.009000             1.000000              6.000000     0.987110   
25%       0.038000            17.000000             77.000000     0.992330   
50%       0.047000            29.000000            118.000000     0.994890   
75%       0.065000            41.000000            156.000000     0.997000   
max       0.611000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  6463.000000  6463.000000  6463.000000  6463.000000  
mean      3.218332     0.531150    10.492825     5.818505  
std       0.160650     0.148913     1.193128     0.873286  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.110000     0.430000     9.500000     5.000000  
50%       3.210000     0.510000    10.300000     6.000000  
75%       3.320000     0.600000    11.300000     6.000000  
max       4.010000     2.000000    14.900000     9.000000

DATA VISUALIOZATION  

In [ ]:
df.columns

Index(['type', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'],
      dtype='object')

In [ ]:
df.shape

(6463, 13)

In [ ]:
df['quality'].value_counts()

6    2820
5    2128
7    1074
4     214
8     192
3      30
9       5
Name: quality, dtype: int64

In [ ]:
df.groupby('quality').mean()

<ipython-input-9-26080c041030>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('quality').mean()


fixed acidity  volatile acidity  citric acid  residual sugar  \
quality                                                                 
3             7.853333          0.517000     0.281000        5.140000   
4             7.281308          0.458084     0.272290        4.125234   
5             7.329699          0.389774     0.307923        5.790602   
6             7.180035          0.313598     0.323734        5.556454   
7             7.131425          0.289055     0.334832        4.746182   
8             6.838542          0.289089     0.331771        5.404688   
9             7.420000          0.298000     0.386000        4.120000   

         chlorides  free sulfur dioxide  total sulfur dioxide   density  \
quality                                                                   
3         0.077033            39.216667            122.033333  0.995744   
4         0.059864            20.745327            103.866822  0.994820   
5         0.064740            30.223919            120.715695  0.995847   
6         0.054154            31.147163            115.385106  0.994560   
7         0.045291            30.409683            108.370577  0.993130   
8         0.041188            34.562500            117.739583  0.992531   
9         0.027400            33.400000            116.000000  0.991460   

               pH  sulphates    alcohol  
quality                                  
3        3.257667   0.506333  10.215000  
4        3.231963   0.505841  10.176636  
5        3.212242   0.526184   9.838759  
6        3.217443   0.532365  10.588475  
7        3.227728   0.547058  11.389572  
8        3.222656   0.513125  11.672917  
9        3.308000   0.466000  12.180000

Define Target Variable (y) and Feature Variables (X)

In [ ]:
y=df['quality']

In [ ]:
y.shape

(6463,)

In [ ]:
X=df.drop(['quality','type'],axis=1)

In [ ]:
X.shape

(6463, 11)

In [ ]:
X

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0             0.270         0.36            20.7      0.045   
1               6.3             0.300         0.34             1.6      0.049   
2               8.1             0.280         0.40             6.9      0.050   
3               7.2             0.230         0.32             8.5      0.058   
4               7.2             0.230         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
6491            6.8             0.620         0.08             1.9      0.068   
6492            6.2             0.600         0.08             2.0      0.090   
6494            6.3             0.510         0.13             2.3      0.076   
6495            5.9             0.645         0.12             2.0      0.075   
6496            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
6491                 28.0                  38.0  0.99651  3.42       0.82   
6492                 32.0                  44.0  0.99490  3.45       0.58   
6494                 29.0                  40.0  0.99574  3.42       0.75   
6495                 32.0                  44.0  0.99547  3.57       0.71   
6496                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  
0         8.8  
1         9.5  
2        10.1  
3         9.9  
4         9.9  
...       ...  
6491      9.5  
6492     10.5  
6494     11.0  
6495     10.2  
6496     11.0  

[6463 rows x 11 columns]

DATA PREPROCESSING

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
ss = StandardScaler()

In [ ]:
X=ss.fit_transform(X)

In [ ]:
X

array([[-0.16778609, -0.42270958,  0.2839587 , ..., -1.35916011,
        -0.5449872 , -1.41892232],
       [-0.70715516, -0.2404789 ,  0.14625658, ...,  0.50839916,
        -0.27635393, -0.83218392],
       [ 0.67979387, -0.36196602,  0.55936296, ...,  0.25939126,
        -0.61214551, -0.32926528],
       ...,
       [-0.70715516,  1.03513588, -1.29961576, ...,  1.25542287,
         1.46976231,  0.42511267],
       [-1.01536606,  1.85517396, -1.36846682, ...,  2.18920251,
         1.20112905, -0.24544551],
       [-0.93831333, -0.17973534,  1.0413204 , ...,  1.06866695,
         0.86533746,  0.42511267]])

Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,stratify=y,random_state=2529)

In [ ]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((4524, 11), (1939, 11), (4524,), (1939,))

Modeling

In [ ]:
from sklearn.svm import SVC

In [ ]:
svc=SVC()

In [ ]:
svc.fit(X_train,y_train)

SVC()

In [ ]:
y_pred=svc.predict(X_test)

In [ ]:
y_pred.shape

(1939,)

In [ ]:
y_pred

array([5, 6, 6, ..., 5, 6, 6])

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[  0   0   3   6   0   0   0]
 [  0   0  40  22   2   0   0]
 [  0   0 383 255   0   0   0]
 [  0   0 174 632  40   0   0]
 [  0   0  10 238  74   0   0]
 [  0   0   0  38  20   0   0]
 [  0   0   0   1   1   0   0]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         9
           4       0.00      0.00      0.00        64
           5       0.63      0.60      0.61       638
           6       0.53      0.75      0.62       846
           7       0.54      0.23      0.32       322
           8       0.00      0.00      0.00        58
           9       0.00      0.00      0.00         2

    accuracy                           0.56      1939
   macro avg       0.24      0.23      0.22      1939
weighted avg       0.53      0.56      0.53      1939



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Model Evaluation

In [ ]:
y=df['quality'].apply(lambda y_value: 1 if y_value>=6 else 0)

In [ ]:
y.value_counts()

1    4091
0    2372
Name: quality, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,stratify=y,random_state=2529)

In [ ]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((4524, 11), (1939, 11), (4524,), (1939,))

Prediction

In [ ]:
from sklearn.svm import SVC

In [ ]:
svc=SVC()

In [ ]:
svc.fit(X_train,y_train)

SVC()

In [ ]:
y_pred=svc.predict(X_test)

In [ ]:
y_pred.shape

(1939,)

In [ ]:
y_pred

array([1, 0, 1, ..., 1, 0, 1])

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[ 457  255]
 [ 158 1069]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.74      0.64      0.69       712
           1       0.81      0.87      0.84      1227

    accuracy                           0.79      1939
   macro avg       0.78      0.76      0.76      1939
weighted avg       0.78      0.79      0.78      1939



In [ ]:
df_new=df.sample(1)

In [ ]:
df_new

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
5823  red            8.6              0.22         0.36             1.9   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
5823      0.064                 53.0                  77.0  0.99604  3.47   

      sulphates  alcohol  quality  
5823       0.87     11.0        7

In [ ]:
df_new.shape

(1, 13)

In [ ]:
X_new=df_new.drop(['quality','type'],axis=1)

In [ ]:
X_new=ss.fit_transform(X_new)

In [ ]:
y_pred_new=svc.predict(X_new)

In [ ]:
y_pred_new

array([1])

EXPLANATION:WE FINALLY DID THE WINEQUALITY PREDICTION USING SUPPORT VECTOR MACHINE and executed successfully.